name: Reusable Quickstart Release Test

on:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      setup-name:
        required: true
        type: string
      gpg-name:
        required: true
        type: string
      path-name:
        required: true
        type: string
      remove-data-name:
        required: true
        type: string
      test-name:
        required: true
        type: string
      legacy:
        required: false
        type: boolean
        default: false
      runs-on:
        required: false
        type: string
        default: 'macos-14'
      test-args:
        required: false
        type: string
        default: 'false'
      test-swift:
        required: false
        type: boolean
        default: true
      test-objc:
        required: false
        type: boolean
        default: false
      xcode-version:
        required: false
        type: string
      pre-test-script:
        required: false
        type: string
    secrets:
      GHASecretsGPGPassphrase1:
        required: true
      RELEASE_TESTING_PAT:
        required: true

jobs:
  quickstart:
    runs-on: ${{ inputs.runs-on }}
    env:
      plist_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
      signin_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
      botaccess: ${{ secrets.RELEASE_TESTING_PAT }}
      LEGACY: ${{ inputs.legacy }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
    - name: Select Xcode
      if: ${{ inputs.xcode-version }}
      run: sudo xcode-select -s /Applications/Xcode_${{ inputs.xcode-version }}.app/Contents/Developer
    - name: Setup testing repo and quickstart
      run: BOT_TOKEN="${{ env.botaccess }}" scripts/setup_quickstart.sh ${{ inputs.setup-name }} nightly_release_testing
    - name: Install Secret GoogleService-Info.plist
      run: |
        scripts/decrypt_gha_secret.sh scripts/gha-encrypted/qs-${{ inputs.gpg-name }}.plist.gpg \
          quickstart-ios/${{ inputs.path-name }}/GoogleService-Info.plist "$plist_secret"
    - name: Pre-test script
      if: ${{ inputs.pre-test-script }}
      run: ${{ inputs.pre-test-script }}
    - name: Test objc quickstart
      if: ${{ inputs.test-objc }}
      run: |
        ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart.sh ${{ inputs.test-name }} ${{ inputs.test-args }})
    - name: Test swift quickstart
      if: ${{ inputs.test-swift }}
      run: |
        ([ -z $plist_secret ] || scripts/third_party/travis/retry.sh scripts/test_quickstart.sh ${{ inputs.test-name }} ${{ inputs.test-args }} swift)
    - name: Remove data before upload
      if: ${{ failure() }}
      run: scripts/remove_data.sh ${{ inputs.remove-data-name }}
    - uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: quickstart_artifacts_${{ inputs.path-name }}
        path: quickstart-ios/
